routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function(){
    return view('home');
});

Route::get('/products/add', 'ProductController@add')->name('products.add');
Route::resource('/products', 'ProductController');

Route::get('/login/google', 'Auth\SocialAuthController@redirectToProvider')->name('google.login');
Route::get('/login/google/callback', 'Auth\SocialAuthController@handleProviderCallback');

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;


class HomeController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('home');
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Product;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $products = Product::all();
        return view('products/products', ['products' => $products]);
    }

    public function add()
    {
        if (Gate::denies('create')) {
            return redirect('/products');
        }
        return view('products/product_add');
    }

    public function store(Request $request)
    {
        if (Gate::denies('create')) {
            return redirect('/products');
        }
        $product = Product::create([
            'name' => $request->name,
            'price' => $request->price,
            'user_id' => Auth::id()
        ]);
        $product->save();
        return redirect()->route('products.index');
    }

    public function show($id)
    {
        $product = Product::find($id);
        return view('products/product_show', ['product' => $product]);
    }

    public function edit($id)
    {
        $product = Product::where('id', $id)->first();
        if (Gate::denies('update', $product)) {
            return redirect('/products');
        }
        return view('products/product_edit', ['product' => $product]);
    }

    public function update(Request $request, $id)
    {
        $product = Product::find($id);
        if (Gate::denies('update', $product)) {

            return redirect('/products');
        }
        $product->update([
            'name' => $request->name,
            'price' => $request->price
        ]);
        $product->save();
        return redirect()->route('products.show', ['id' => $product->id]);
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        if (Gate::denies('delete', $product)) {
            return redirect('/products');
        }

        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <h3>Marketplace</h3>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @auth
                        You are logged in!
                    @endauth
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else



                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-success" href="{{route('products.add')}}">Add Product</a>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/products/product_add.blade.php
@extends('layouts.app')

@section('title', 'Marketplace')

@section('content')

    <h2>MarketPlace</h2>
    <form action="{{route('products.store')}}" method="post">

        {{csrf_field()}}

        <input class="form-control" type="text" name="name" placeholder="Name" value="{{ old('name') }}">
        @if($errors->has('name'))
            <div class="alert alert-danger">{{$errors->first('name')}}</div>
        @endif

        <input class="form-control" type="text" name="price" placeholder="Price" value="{{ old('price') }}">
        @if($errors->has('price'))
            <div class="alert alert-danger">{{$errors->first('price')}}</div>
        @endif

        <button style="font-weight: 600;" class="btn btn-success" type="submit">Save</button>

    </form>

@endsection

resources/views/products/product_edit.blade.php
@extends('layouts.app')

@section('title', 'Marketplace')

@section('content')

    <form action="{{route('products.update', ['id' => $product->id])}}" method="post">

        {{ method_field('PUT') }}
        {{csrf_field()}}

        <input class="form-control" type="text" name="name" placeholder="Name"
               value="{{ old('name')?:$product->name }}">
        @if($errors->has('name'))
            <div class="alert alert-danger">{{$errors->first('name')}}</div>
        @endif

        <input class="form-control" type="text" name="price" placeholder="Price"
               value="{{ old('price')?:$product->price }}">
        @if($errors->has('price'))
            <div class="alert alert-danger">{{$errors->first('price')}}</div>
        @endif

        <button style="font-weight: 600;" class="btn btn-success" type="submit">Save</button>

    </form>

@endsection

resources/views/products/product_show.blade.php
@extends('layouts.app')

@section('title', 'Marketplace')

@section('content')

    <h3>{{$product->name}}</h3>
    @if (Auth::user()->can('update', $product))
        <a style="font-weight: 300;" class="edit-button btn btn-info"
           href="{{route('products.edit', ['id' => $product->id])}}">Edit</a>

        <form style="display: inline-block;" action="{{ route('products.destroy', ['id' => $product->id]) }}"
              method="POST">

            {{ csrf_field() }}
            {{ method_field('DELETE') }}

            <button style="font-weight: 300;" class="delete-button btn btn-danger" type="submit">Delete
            </button>
        </form>
    @endif

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>Name</th>
                <td>
                    <h4>{{$product->name}}</h4>
                </td>
            </tr>
            <tr>
                <th>Price</th>
                <td>
                    <h4>{{$product->price}}</h4>
                </td>
            </tr>
        </tbody>
    </table>

@endsection

resources/views/products/products.blade.php
@extends('layouts.app')

@section('title', 'Marketplace')

@section('content')

    <h2>MarketPlace</h2>
    @if($products->count() > 0)
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($products as $product)
                <tr>
                    <td>
                        <h4><a href="{{route('products.show', ['id' => $product->id])}}">{{ $product->name}}</a>
                        </h4>
                    </td>
                    <td>
                        <h4>{{ $product->price }}</h4>
                    </td>
                    @if (Auth::user()->can('update', $product))
                            <td>
                                <a style="font-weight: 600;" class="btn btn-info"
                                   href="{{route('products.edit', ['id' => $product->id])}}">Edit</a>
                                <form style="display: inline-block;"
                                      action="{{ route('products.destroy', ['id' => $product->id]) }}" method="POST">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}

                                    <button style="font-weight: 300;" class="btn btn-danger" type="submit">Delete
                                    </button>
                                </form>
                            </td>
                     @endif
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <p>No products</p>
    @endif

@endsection